for i = 0, 9 do
	defkey("^(k" .. i .. ")", "F" .. i)
end 
defkey("^(k;)", "F10")
defkey("^(F1)", "F11")
defkey("^(F2)", "F12")
defkey("^(ku)", "UP")
defkey("^(kd)", "DOWN")
defkey("^(kl)", "LEFT")
defkey("^(kr)", "RIGHT")
defkey("^(kP)", "PPAGE")
defkey("^(kN)", "NPAGE")
defkey("^(kh)", "HOME")
defkey("^(@7)", "END")
defkey("^(K1)", "A1")
defkey("^(K3)", "A3")
defkey("^(K2)", "B2")
defkey("^(K4)", "C1")
defkey("^(K5)", "C3")
defkey("^(%0)", "REDO")
defkey("^(&8)", "UNDO")
defkey("^(kb)", "BACKSPACE")
defkey("^(@8)", "ENTER")
defkey("^(kD)", "DELETE")
