# Sanity checks.
IF (NOT CMAKE_C_COMPILER MATCHES "gcc")
	MESSAGE(SEND_ERROR "moonshine requires gcc to compile")
ELSE()
	MESSAGE(STATUS "Good, we have gcc")
ENDIF()

IF (NOT PKGCONFIG_EXECUTABLE)
	MESSAGE(SEND_ERROR "moonshine requires pkg-config")
ELSE()
	MESSAGE(STATUS "Good, we have pkg-config")
ENDIF()

IF (NOT GLIB_FOUND)
	MESSAGE(SEND_ERROR "moonshine requires glib-2.0")
ELSE()
	MESSAGE(STATUS "Good, we have glib")
ENDIF()

IF (NOT GNET_FOUND)
	MESSAGE(SEND_ERROR "moonshine requires gnet-2.0")
ELSE()
	MESSAGE(STATUS "Good, we have gnet")
ENDIF()

IF (NOT LUA_FOUND)
	MESSAGE(SEND_ERROR "moonshine requires lua")
ELSE()
	MESSAGE(STATUS "Good, we have lua")
ENDIF()

IF (SLANG_FOUND)
	MESSAGE(STATUS "Good, we have slang")
	INCLUDE (cmake/SlangVersion.cmake)

	IF (SLANG_VERSION LESS 20000)
		MESSAGE(SEND_ERROR "... but moonshine requires slang-2")
	ELSE ()
		MESSAGE(STATUS "Good, slang is version 2")
	ENDIF ()
ELSE ()
	MESSAGE(SEND_ERROR "moonshine requires slang-2")
ENDIF()
