MARK_AS_ADVANCED(LPEG_RESULT)

IF (LPEG_RESULT EQUAL 0)
    SET(LPEG_FOUND TRUE)
ELSE(LPEG_RESULT EQUAL 0)
    FIND_PROGRAM(LUA lua)
    EXECUTE_PROCESS(
        COMMAND ${LUA} -e "require 'lpeg'"
        RESULT_VARIABLE LPEG_RESULT
        OUTPUT_QUIET
        ERROR_QUIET)

    IF(${LPEG_RESULT} EQUAL 0)
        SET(LPEG_RESULT "${LPEG_RESULT}" CACHE STRING "lpeg result")
        SET(LPEG_FOUND TRUE)
    ELSE(${LPEG_RESULT} EQUAL 0)
        SET(LPEG_FOUND FALSE)
    ENDIF(${LPEG_RESULT} EQUAL 0)

    IF (LPEG_FOUND)
        IF (NOT LPEG_FIND_QUIETLY)
            MESSAGE(STATUS "Found lpeg")
        ENDIF (NOT LPEG_FIND_QUIETLY)
    ELSE (LPEG_FOUND)
        IF (LPEG_FIND_REQUIRED)
            MESSAGE(FATAL_ERROR "Could not find lpeg")
        ENDIF (LPEG_FIND_REQUIRED)
    ENDIF (LPEG_FOUND)
ENDIF(LPEG_RESULT EQUAL 0)
