MARK_AS_ADVANCED(LUABIT_RESULT)

IF (LUABIT_RESULT EQUAL 0)
    SET(LUABIT_FOUND TRUE)
ELSE(LUABIT_RESULT EQUAL 0)
    FIND_PROGRAM(LUA lua)
    EXECUTE_PROCESS(
        COMMAND ${LUA} -e "require 'bit'"
        RESULT_VARIABLE LUABIT_RESULT
        OUTPUT_QUIET
        ERROR_QUIET)

    IF(${LUABIT_RESULT} EQUAL 0)
        SET(LUABIT_RESULT "${LUABIT_RESULT}" CACHE STRING "luabit result")
        SET(LUABIT_FOUND TRUE)
    ELSE(${LUABIT_RESULT} EQUAL 0)
        SET(LUABIT_FOUND FALSE)
    ENDIF(${LUABIT_RESULT} EQUAL 0)

    IF (LUABIT_FOUND)
        IF (NOT LUABIT_FIND_QUIETLY)
            MESSAGE(STATUS "Found bit")
        ENDIF (NOT LUABIT_FIND_QUIETLY)
    ELSE (LUABIT_FOUND)
        IF (LUABIT_FIND_REQUIRED)
            MESSAGE(FATAL_ERROR "Could not find bit")
        ENDIF (LUABIT_FIND_REQUIRED)
    ENDIF (LUABIT_FOUND)
ENDIF(LUABIT_RESULT EQUAL 0)
